# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('durata', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tipologia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dipartimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(default='materia', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('titolo', models.CharField(max_length=100)),
                ('tipologia', models.CharField(max_length=50)),
                ('data_immissione', models.DateField()),
                ('durata', models.PositiveSmallIntegerField()),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Corso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateField()),
                ('approvato', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Docente')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Proposta')),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=20)),
                ('anno_corso', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('crediti', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('corso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Corso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='richiesta',
            name='studente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Studente'),
        ),
        migrations.AddField(
            model_name='corso',
            name='dipartimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Dipartimento'),
        ),
    ]
