# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sede', models.CharField(max_length=30)),
                ('pIva', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField()),
                ('approvata', models.BooleanField(default=False)),
                ('rifiutata', models.BooleanField(default=False)),
                ('pubblicata', models.BooleanField(default=False)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Azienda')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Docente')),
            ],
        ),
        migrations.RenameField(
            model_name='dipartimento',
            old_name='provincia',
            new_name='sede',
        ),
        migrations.RenameField(
            model_name='richiesta',
            old_name='approvato',
            new_name='accettata',
        ),
        migrations.AddField(
            model_name='proposta',
            name='archiviata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposta',
            name='inRichiesta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposta',
            name='richiedibile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='approvata',
            field=models.BooleanField(default=False),
        ),
    ]
