# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 10:11
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20170802_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azienda',
            options={'verbose_name_plural': 'Aziende'},
        ),
        migrations.AlterModelOptions(
            name='corso',
            options={'verbose_name_plural': 'Corsi'},
        ),
        migrations.AlterModelOptions(
            name='dipartimento',
            options={'verbose_name_plural': 'Dipartimenti'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name_plural': 'Docenti'},
        ),
        migrations.AlterModelOptions(
            name='offerta',
            options={'verbose_name_plural': 'Offerte tirocinio aziende'},
        ),
        migrations.AlterModelOptions(
            name='proposta',
            options={'verbose_name_plural': 'Proposte'},
        ),
        migrations.AlterModelOptions(
            name='richiesta',
            options={'verbose_name_plural': 'Richieste'},
        ),
        migrations.AlterModelOptions(
            name='studente',
            options={'verbose_name_plural': 'Studenti'},
        ),
        migrations.AddField(
            model_name='azienda',
            name='user',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corso',
            name='durata',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='corso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='corso',
            name='tipologia',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dipartimento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dipartimento',
            name='sede',
            field=models.CharField(max_length=200),
        ),
    ]
