# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 15:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_offerta_corso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studente',
            name='anno_corso',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
