# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170815_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='codice',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
