# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_offerta_data_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerta',
            name='data_pub',
        ),
    ]
