# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_offerta_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='data_pub',
            field=models.DateField(default=datetime.datetime(2017, 9, 19, 10, 2, 3, 708749)),
        ),
    ]
