# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20170919_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='data_immissione',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
