# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20170921_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='tipologia',
            field=models.CharField(choices=[('triennale', 'triennale'), ('magistrale', 'magistrale'), ('magistrale a ciclo unico', 'magistrale a ciclo unico'), ('dottorato', 'dottorato')], max_length=30),
        ),
    ]
