# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20170921_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Docente'),
        ),
    ]
