# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20170921_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='azienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Azienda'),
        ),
    ]
