# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20170928_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='data_rifiuto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
