# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_offerta_data_rifiuto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_richiesta', models.DateField()),
                ('approvata', models.BooleanField(default=False)),
                ('accettata', models.BooleanField(default=False)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Azienda')),
                ('offerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Offerta')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Studente')),
            ],
            options={
                'verbose_name_plural': 'Richieste per tirocinio',
            },
        ),
        migrations.AlterModelOptions(
            name='richiesta',
            options={'verbose_name_plural': 'Richieste per tesi o AP'},
        ),
    ]
