# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20171005_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='azienda',
        ),
    ]
