# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20171005_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerta',
            name='macrostato',
            field=models.CharField(choices=[('offerta richiedibile', ' offerta richiedibile'), ('offerta non richiedibile', ' offerta non richiedibile')], default=' offerta non richiedibile', max_length=100),
        ),
        migrations.AddField(
            model_name='offerta',
            name='stato',
            field=models.CharField(choices=[('offerta senza richieste', 'offerta senza richieste'), ('offerta con richieste', 'offerta con richieste'), ('offerta assegnata', 'offerta assegnata'), ('offerta archiviata', 'offerta archiviata')], default='offerta senza richieste', max_length=100),
        ),
        migrations.AddField(
            model_name='offerta',
            name='stato_valutazione',
            field=models.CharField(choices=[('in attesa di valutazione', 'in attesa di valutazione'), ('approvata', 'approvata'), ('rifiutata', 'rifiutata')], default='in attesa di valutazione', max_length=100),
        ),
    ]
