# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20171005_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerta',
            name='approvata',
        ),
        migrations.RemoveField(
            model_name='offerta',
            name='archiviata',
        ),
        migrations.RemoveField(
            model_name='offerta',
            name='rifiutata',
        ),
    ]
