# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20171016_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='durata',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
