# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20171020_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richiesta',
            name='accettata',
        ),
        migrations.RemoveField(
            model_name='richiesta',
            name='approvata',
        ),
        migrations.RemoveField(
            model_name='richiestao',
            name='accettata',
        ),
        migrations.RemoveField(
            model_name='richiestao',
            name='approvata',
        ),
        migrations.AddField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(choices=[('pendente', 'pendente'), ('approvata', 'approvata'), ('accettata', 'accettata')], default='pendente', max_length=50),
        ),
        migrations.AddField(
            model_name='richiestao',
            name='stato',
            field=models.CharField(choices=[('pendente', 'pendente'), ('approvata', 'approvata'), ('accettata', 'accettata')], default='pendente', max_length=50),
        ),
    ]
