from .views import *
from .views_ajax import *
from .views_accesso import *
from .views_lista_richiedenti import *
from .views_offerta_dettaglio import *
from .views_proposta_dettaglio import *
from .views_registrazione import *
from .views_spazio_aziende import *
from .views_spazio_docenti import *
from .views_spazio_studenti import *